/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Sign_up (void)
{
  GtkWidget *Sign_up;
  GtkWidget *fixed1;
  GtkWidget *entryFirstName;
  GtkWidget *entryLastName;
  GtkWidget *LastName;
  GtkWidget *entryUsername;
  GtkWidget *Username;
  GtkWidget *entryPassword;
  GtkWidget *Role;
  GtkWidget *Password;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkWidget *Nb;
  GtkWidget *buttonSignup;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label8;
  GtkWidget *FirstName;
  GtkWidget *Signup;
  GtkWidget *label72;

  Sign_up = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Sign_up, 700, 500);
  gtk_window_set_title (GTK_WINDOW (Sign_up), _("Sign up"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Sign_up), fixed1);

  entryFirstName = gtk_entry_new ();
  gtk_widget_show (entryFirstName);
  gtk_fixed_put (GTK_FIXED (fixed1), entryFirstName, 160, 104);
  gtk_widget_set_size_request (entryFirstName, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryFirstName), 8226);

  entryLastName = gtk_entry_new ();
  gtk_widget_show (entryLastName);
  gtk_fixed_put (GTK_FIXED (fixed1), entryLastName, 160, 150);
  gtk_widget_set_size_request (entryLastName, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryLastName), 8226);

  LastName = gtk_label_new (_("Last Name :"));
  gtk_widget_show (LastName);
  gtk_fixed_put (GTK_FIXED (fixed1), LastName, 32, 150);
  gtk_widget_set_size_request (LastName, 112, 32);

  entryUsername = gtk_entry_new ();
  gtk_widget_show (entryUsername);
  gtk_fixed_put (GTK_FIXED (fixed1), entryUsername, 160, 200);
  gtk_widget_set_size_request (entryUsername, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryUsername), 8226);

  Username = gtk_label_new (_("Username:"));
  gtk_widget_show (Username);
  gtk_fixed_put (GTK_FIXED (fixed1), Username, 32, 200);
  gtk_widget_set_size_request (Username, 112, 32);

  entryPassword = gtk_entry_new ();
  gtk_widget_show (entryPassword);
  gtk_fixed_put (GTK_FIXED (fixed1), entryPassword, 160, 250);
  gtk_widget_set_size_request (entryPassword, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (entryPassword), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryPassword), 8226);

  Role = gtk_label_new (_("Role"));
  gtk_widget_show (Role);
  gtk_fixed_put (GTK_FIXED (fixed1), Role, 32, 300);
  gtk_widget_set_size_request (Role, 112, 32);

  Password = gtk_label_new (_("Password"));
  gtk_widget_show (Password);
  gtk_fixed_put (GTK_FIXED (fixed1), Password, 32, 250);
  gtk_widget_set_size_request (Password, 112, 32);

  spinbutton2_adj = gtk_adjustment_new (1, 1, 6, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton2, 200, 296);
  gtk_widget_set_size_request (spinbutton2, 70, 34);

  Nb = gtk_label_new (_("(1 : Admin, 2:Technicien, 3:Nutrionist,4:Foyer Agent,5:Restaurant Agent,6:Student.)"));
  gtk_widget_show (Nb);
  gtk_fixed_put (GTK_FIXED (fixed1), Nb, 16, 360);
  gtk_widget_set_size_request (Nb, 564, 12);

  buttonSignup = gtk_button_new ();
  gtk_widget_show (buttonSignup);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonSignup, 112, 424);
  gtk_widget_set_size_request (buttonSignup, 162, 29);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttonSignup), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("Sign Up"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox1), label8, FALSE, FALSE, 0);

  FirstName = gtk_label_new (_("First Name :"));
  gtk_widget_show (FirstName);
  gtk_fixed_put (GTK_FIXED (fixed1), FirstName, 40, 96);
  gtk_widget_set_size_request (FirstName, 112, 32);

  Signup = gtk_label_new (_("<b><span foreground=\"yellow\" font-desc=\"bold 12\">JOIN US </span></b>"));
  gtk_widget_show (Signup);
  gtk_fixed_put (GTK_FIXED (fixed1), Signup, 120, 32);
  gtk_widget_set_size_request (Signup, 120, 32);
  gtk_label_set_use_markup (GTK_LABEL (Signup), TRUE);

  label72 = gtk_label_new ("");
  gtk_widget_show (label72);
  gtk_fixed_put (GTK_FIXED (fixed1), label72, 352, 192);
  gtk_widget_set_size_request (label72, 320, 40);

  g_signal_connect ((gpointer) buttonSignup, "clicked",
                    G_CALLBACK (on_buttonSignup_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Sign_up, Sign_up, "Sign_up");
  GLADE_HOOKUP_OBJECT (Sign_up, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Sign_up, entryFirstName, "entryFirstName");
  GLADE_HOOKUP_OBJECT (Sign_up, entryLastName, "entryLastName");
  GLADE_HOOKUP_OBJECT (Sign_up, LastName, "LastName");
  GLADE_HOOKUP_OBJECT (Sign_up, entryUsername, "entryUsername");
  GLADE_HOOKUP_OBJECT (Sign_up, Username, "Username");
  GLADE_HOOKUP_OBJECT (Sign_up, entryPassword, "entryPassword");
  GLADE_HOOKUP_OBJECT (Sign_up, Role, "Role");
  GLADE_HOOKUP_OBJECT (Sign_up, Password, "Password");
  GLADE_HOOKUP_OBJECT (Sign_up, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (Sign_up, Nb, "Nb");
  GLADE_HOOKUP_OBJECT (Sign_up, buttonSignup, "buttonSignup");
  GLADE_HOOKUP_OBJECT (Sign_up, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Sign_up, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Sign_up, image1, "image1");
  GLADE_HOOKUP_OBJECT (Sign_up, label8, "label8");
  GLADE_HOOKUP_OBJECT (Sign_up, FirstName, "FirstName");
  GLADE_HOOKUP_OBJECT (Sign_up, Signup, "Signup");
  GLADE_HOOKUP_OBJECT (Sign_up, label72, "label72");

  return Sign_up;
}

GtkWidget*
create_Login (void)
{
  GtkWidget *Login;
  GtkWidget *fixed2;
  GtkWidget *entryUsername_Login;
  GtkWidget *Username_Login;
  GtkWidget *entryPassword_Login;
  GtkWidget *Password_Login;
  GtkWidget *buttonLogin;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label12;
  GtkWidget *label66;
  GtkWidget *label67;
  GtkWidget *button4;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image20;
  GtkWidget *label68;
  GtkWidget *label6;

  Login = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Login, 400, -1);
  gtk_window_set_title (GTK_WINDOW (Login), _("Login"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (Login), fixed2);

  entryUsername_Login = gtk_entry_new ();
  gtk_widget_show (entryUsername_Login);
  gtk_fixed_put (GTK_FIXED (fixed2), entryUsername_Login, 180, 120);
  gtk_widget_set_size_request (entryUsername_Login, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryUsername_Login), 8226);

  Username_Login = gtk_label_new (_("Username :"));
  gtk_widget_show (Username_Login);
  gtk_fixed_put (GTK_FIXED (fixed2), Username_Login, 50, 120);
  gtk_widget_set_size_request (Username_Login, 125, 25);

  entryPassword_Login = gtk_entry_new ();
  gtk_widget_show (entryPassword_Login);
  gtk_fixed_put (GTK_FIXED (fixed2), entryPassword_Login, 180, 170);
  gtk_widget_set_size_request (entryPassword_Login, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (entryPassword_Login), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryPassword_Login), 8226);

  Password_Login = gtk_label_new (_("Password:"));
  gtk_widget_show (Password_Login);
  gtk_fixed_put (GTK_FIXED (fixed2), Password_Login, 50, 170);
  gtk_widget_set_size_request (Password_Login, 125, 25);

  buttonLogin = gtk_button_new ();
  gtk_widget_show (buttonLogin);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonLogin, 128, 224);
  gtk_widget_set_size_request (buttonLogin, 150, 29);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (buttonLogin), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("Login"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox2), label12, FALSE, FALSE, 0);

  label66 = gtk_label_new (_("<b><span foreground=\"yellow\" font-desc=\"Serif bold 13\"  > WELCOME BACK </span></b>"));
  gtk_widget_show (label66);
  gtk_fixed_put (GTK_FIXED (fixed2), label66, 112, 24);
  gtk_widget_set_size_request (label66, 200, 48);
  gtk_label_set_use_markup (GTK_LABEL (label66), TRUE);

  label67 = gtk_label_new (_("<b><span foreground=\"green\" font-desc=\"bold 12\">Dont have an account?</span></b>"));
  gtk_widget_show (label67);
  gtk_fixed_put (GTK_FIXED (fixed2), label67, 24, 296);
  gtk_widget_set_size_request (label67, 200, 30);
  gtk_label_set_use_markup (GTK_LABEL (label67), TRUE);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed2), button4, 272, 296);
  gtk_widget_set_size_request (button4, 104, 32);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button4), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image20 = gtk_image_new_from_stock ("gtk-redo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox14), image20, FALSE, FALSE, 0);

  label68 = gtk_label_new_with_mnemonic (_("Sign Up"));
  gtk_widget_show (label68);
  gtk_box_pack_start (GTK_BOX (hbox14), label68, FALSE, FALSE, 0);

  label6 = gtk_label_new ("");
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed2), label6, 64, 272);
  gtk_widget_set_size_request (label6, 248, 29);
  gtk_label_set_use_markup (GTK_LABEL (label6), TRUE);

  g_signal_connect ((gpointer) buttonLogin, "clicked",
                    G_CALLBACK (on_buttonLogin_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Login, Login, "Login");
  GLADE_HOOKUP_OBJECT (Login, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Login, entryUsername_Login, "entryUsername_Login");
  GLADE_HOOKUP_OBJECT (Login, Username_Login, "Username_Login");
  GLADE_HOOKUP_OBJECT (Login, entryPassword_Login, "entryPassword_Login");
  GLADE_HOOKUP_OBJECT (Login, Password_Login, "Password_Login");
  GLADE_HOOKUP_OBJECT (Login, buttonLogin, "buttonLogin");
  GLADE_HOOKUP_OBJECT (Login, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Login, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Login, image2, "image2");
  GLADE_HOOKUP_OBJECT (Login, label12, "label12");
  GLADE_HOOKUP_OBJECT (Login, label66, "label66");
  GLADE_HOOKUP_OBJECT (Login, label67, "label67");
  GLADE_HOOKUP_OBJECT (Login, button4, "button4");
  GLADE_HOOKUP_OBJECT (Login, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (Login, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (Login, image20, "image20");
  GLADE_HOOKUP_OBJECT (Login, label68, "label68");
  GLADE_HOOKUP_OBJECT (Login, label6, "label6");

  return Login;
}

GtkWidget*
create_Admin (void)
{
  GtkWidget *Admin;
  GtkWidget *fixed3;
  GtkWidget *welcome;
  GtkWidget *button6;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image22;
  GtkWidget *label97;
  GtkWidget *notebook1;
  GtkWidget *fixed6;
  GtkWidget *entry6;
  GtkWidget *entry7;
  GtkWidget *entry8;
  GtkWidget *entry9;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkWidget *add_add;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image9;
  GtkWidget *label37;
  GtkWidget *label33;
  GtkWidget *label32;
  GtkWidget *label31;
  GtkWidget *label51;
  GtkWidget *Display_add;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image10;
  GtkWidget *label38;
  GtkWidget *label86;
  GtkWidget *label36;
  GtkWidget *label103;
  GtkWidget *label71;
  GtkWidget *label34;
  GtkWidget *label35;
  GtkWidget *vseparator2;
  GtkWidget *label26;
  GtkWidget *fixed7;
  GtkWidget *entry10;
  GtkWidget *label50;
  GtkWidget *label39;
  GtkWidget *button1;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image14;
  GtkWidget *label52;
  GtkWidget *label98;
  GtkWidget *checkbuttonno;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image24;
  GtkWidget *label100;
  GtkWidget *Delete;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image11;
  GtkWidget *label40;
  GtkWidget *checkbuttonyes;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image23;
  GtkWidget *label99;
  GtkWidget *label101;
  GtkWidget *label102;
  GtkWidget *label27;
  GtkWidget *fixed8;
  GtkWidget *entry11;
  GtkWidget *label57;
  GtkWidget *label58;
  GtkWidget *label49;
  GtkWidget *label83;
  GtkWidget *label87;
  GtkWidget *label88;
  GtkWidget *label89;
  GtkWidget *label91;
  GtkWidget *label92;
  GtkWidget *label93;
  GtkWidget *label94;
  GtkWidget *label90;
  GtkWidget *label95;
  GtkWidget *label96;
  GtkWidget *button2;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image15;
  GtkWidget *label53;
  GtkWidget *vseparator1;
  GtkWidget *button_search;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image12;
  GtkWidget *label42;
  GtkWidget *label104;
  GtkWidget *comboboxZA;
  GtkWidget *label28;
  GtkWidget *fixed9;
  GtkWidget *entry12;
  GtkWidget *entry13;
  GtkWidget *entry14;
  GtkWidget *entry15;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *label45;
  GtkWidget *label69;
  GtkWidget *label70;
  GtkWidget *button3;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image16;
  GtkWidget *label54;
  GtkWidget *Update_Update;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image13;
  GtkWidget *label48;
  GtkWidget *label43;
  GtkWidget *label44;
  GtkWidget *label46;
  GtkWidget *label47;
  GtkWidget *vseparator3;
  GtkWidget *label29;
  GtkWidget *fixed11;
  GtkWidget *calcul;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image19;
  GtkWidget *label62;
  GtkWidget *radiobutton7;
  GSList *radiobutton7_group = NULL;
  GtkWidget *label60;
  GtkWidget *radiobutton5;
  GtkWidget *radiobutton1;
  GtkWidget *radiobutton2;
  GtkWidget *radiobutton4;
  GtkWidget *radiobutton6;
  GtkWidget *label63;
  GtkWidget *radiobutton3;
  GtkWidget *label61;
  GtkWidget *label59;

  Admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Admin), _("Admin"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (Admin), fixed3);
  gtk_widget_set_size_request (fixed3, 800, 600);

  welcome = gtk_label_new_with_mnemonic (_("<b><span font-desc=\"black 16\"   foreground=\"gold\"> Welcome to admin espace  </span></b>"));
  gtk_widget_show (welcome);
  gtk_fixed_put (GTK_FIXED (fixed3), welcome, 264, 0);
  gtk_widget_set_size_request (welcome, 330, 80);
  gtk_label_set_use_markup (GTK_LABEL (welcome), TRUE);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed3), button6, 688, 32);
  gtk_widget_set_size_request (button6, 96, 40);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button6), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image22 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox16), image22, FALSE, FALSE, 0);

  label97 = gtk_label_new_with_mnemonic (_("Logout"));
  gtk_widget_show (label97);
  gtk_box_pack_start (GTK_BOX (hbox16), label97, FALSE, FALSE, 0);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed3), notebook1, 80, 112);
  gtk_widget_set_size_request (notebook1, 624, 512);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed6);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed6), entry6, 136, 128);
  gtk_widget_set_size_request (entry6, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed6), entry7, 136, 184);
  gtk_widget_set_size_request (entry7, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed6), entry8, 136, 240);
  gtk_widget_set_size_request (entry8, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed6), entry9, 136, 304);
  gtk_widget_set_size_request (entry9, 172, 34);
  gtk_entry_set_visibility (GTK_ENTRY (entry9), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  spinbutton1_adj = gtk_adjustment_new (1, 1, 6, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton1, 136, 360);
  gtk_widget_set_size_request (spinbutton1, 70, 34);

  add_add = gtk_button_new ();
  gtk_widget_show (add_add);
  gtk_fixed_put (GTK_FIXED (fixed6), add_add, 408, 160);
  gtk_widget_set_size_request (add_add, 150, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (add_add), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image9 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox3), image9, FALSE, FALSE, 0);

  label37 = gtk_label_new_with_mnemonic (_("Add User"));
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox3), label37, FALSE, FALSE, 0);

  label33 = gtk_label_new (_("Username"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed6), label33, 16, 240);
  gtk_widget_set_size_request (label33, 100, 30);

  label32 = gtk_label_new (_("Last Name"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed6), label32, 16, 184);
  gtk_widget_set_size_request (label32, 100, 30);

  label31 = gtk_label_new (_("First Name"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed6), label31, 16, 128);
  gtk_widget_set_size_request (label31, 100, 30);

  label51 = gtk_label_new (_("<b><span foreground=\"gray\" font-desc=\"Serif bold 13\"  > Enter your information please ! </span></b>"));
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed6), label51, 24, 48);
  gtk_widget_set_size_request (label51, 350, 30);
  gtk_label_set_use_markup (GTK_LABEL (label51), TRUE);

  Display_add = gtk_button_new ();
  gtk_widget_show (Display_add);
  gtk_fixed_put (GTK_FIXED (fixed6), Display_add, 408, 240);
  gtk_widget_set_size_request (Display_add, 150, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (Display_add), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image10 = gtk_image_new_from_stock ("gtk-go-down", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox4), image10, FALSE, FALSE, 0);

  label38 = gtk_label_new_with_mnemonic (_("Display Users"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox4), label38, FALSE, FALSE, 0);

  label86 = gtk_label_new ("");
  gtk_widget_show (label86);
  gtk_fixed_put (GTK_FIXED (fixed6), label86, 312, 248);
  gtk_widget_set_size_request (label86, 96, 32);

  label36 = gtk_label_new (_("1/  Admin\n2/  Technicien\n3/  Nutrionist \n4/  Foyer Agent\n5/  Restaurant Agent\n6/  Student"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed6), label36, 216, 344);
  gtk_widget_set_size_request (label36, 160, 136);

  label103 = gtk_label_new (_("<b><span foreground=\"red\"font-desc=\" 10\"  > User Name must be unique</span></b>"));
  gtk_widget_show (label103);
  gtk_fixed_put (GTK_FIXED (fixed6), label103, 72, 256);
  gtk_widget_set_size_request (label103, 224, 72);
  gtk_label_set_use_markup (GTK_LABEL (label103), TRUE);

  label71 = gtk_label_new (_("<b><span foreground=\"red\"font-desc=\" 13\"  > NB  : </span></b>"));
  gtk_widget_show (label71);
  gtk_fixed_put (GTK_FIXED (fixed6), label71, 40, 280);
  gtk_widget_set_size_request (label71, 64, 24);
  gtk_label_set_use_markup (GTK_LABEL (label71), TRUE);

  label34 = gtk_label_new (_("Password"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed6), label34, 16, 304);
  gtk_widget_set_size_request (label34, 100, 30);

  label35 = gtk_label_new (_("Role"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed6), label35, 8, 360);
  gtk_widget_set_size_request (label35, 100, 30);

  vseparator2 = gtk_vseparator_new ();
  gtk_widget_show (vseparator2);
  gtk_fixed_put (GTK_FIXED (fixed6), vseparator2, 384, 0);
  gtk_widget_set_size_request (vseparator2, 16, 456);

  label26 = gtk_label_new (_("<b><span foreground=\"turquoise\">ADD</span></b>"));
  gtk_widget_show (label26);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label26);
  gtk_widget_set_size_request (label26, 100, 30);
  gtk_label_set_use_markup (GTK_LABEL (label26), TRUE);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed7);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed7), entry10, 304, 152);
  gtk_widget_set_size_request (entry10, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  label50 = gtk_label_new (_("<b><span foreground=\"gray\" font-desc=\"Serif bold 15\"  > who you wanna delete ? </span></b>"));
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (fixed7), label50, 160, 56);
  gtk_widget_set_size_request (label50, 300, 50);
  gtk_label_set_use_markup (GTK_LABEL (label50), TRUE);

  label39 = gtk_label_new (_("<b><span font-desc=\" 13\"  > Username </span></b>"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed7), label39, 128, 152);
  gtk_widget_set_size_request (label39, 150, 30);
  gtk_label_set_use_markup (GTK_LABEL (label39), TRUE);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed7), button1, 336, 296);
  gtk_widget_set_size_request (button1, 150, 40);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button1), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image14 = gtk_image_new_from_stock ("gtk-go-down", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox8), image14, FALSE, FALSE, 0);

  label52 = gtk_label_new_with_mnemonic (_("Display Users"));
  gtk_widget_show (label52);
  gtk_box_pack_start (GTK_BOX (hbox8), label52, FALSE, FALSE, 0);

  label98 = gtk_label_new (_("<b><span foreground=\"orange\">Are you sure ?</span></b>"));
  gtk_widget_show (label98);
  gtk_fixed_put (GTK_FIXED (fixed7), label98, 128, 232);
  gtk_widget_set_size_request (label98, 112, 24);
  gtk_label_set_use_markup (GTK_LABEL (label98), TRUE);

  checkbuttonno = gtk_check_button_new ();
  gtk_widget_show (checkbuttonno);
  gtk_fixed_put (GTK_FIXED (fixed7), checkbuttonno, 424, 232);
  gtk_widget_set_size_request (checkbuttonno, 118, 23);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbuttonno), TRUE);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (checkbuttonno), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image24 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox18), image24, FALSE, FALSE, 0);

  label100 = gtk_label_new_with_mnemonic (_("   NO"));
  gtk_widget_show (label100);
  gtk_box_pack_start (GTK_BOX (hbox18), label100, FALSE, FALSE, 0);

  Delete = gtk_button_new ();
  gtk_widget_show (Delete);
  gtk_fixed_put (GTK_FIXED (fixed7), Delete, 136, 296);
  gtk_widget_set_size_request (Delete, 150, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (Delete), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image11 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox5), image11, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("Delete User"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox5), label40, FALSE, FALSE, 0);

  checkbuttonyes = gtk_check_button_new ();
  gtk_widget_show (checkbuttonyes);
  gtk_fixed_put (GTK_FIXED (fixed7), checkbuttonyes, 272, 232);
  gtk_widget_set_size_request (checkbuttonyes, 118, 23);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (checkbuttonyes), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image23 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox17), image23, FALSE, FALSE, 0);

  label99 = gtk_label_new_with_mnemonic (_("YES"));
  gtk_widget_show (label99);
  gtk_box_pack_start (GTK_BOX (hbox17), label99, FALSE, FALSE, 0);

  label101 = gtk_label_new ("");
  gtk_widget_show (label101);
  gtk_fixed_put (GTK_FIXED (fixed7), label101, 256, 264);
  gtk_widget_set_size_request (label101, 112, 24);

  label102 = gtk_label_new ("");
  gtk_widget_show (label102);
  gtk_fixed_put (GTK_FIXED (fixed7), label102, 232, 368);
  gtk_widget_set_size_request (label102, 200, 32);

  label27 = gtk_label_new (_("<b><span foreground=\"turquoise\" >DELETE</span></b>"));
  gtk_widget_show (label27);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label27);
  gtk_widget_set_size_request (label27, 100, 30);
  gtk_label_set_use_markup (GTK_LABEL (label27), TRUE);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed8);

  entry11 = gtk_entry_new ();
  gtk_widget_show (entry11);
  gtk_fixed_put (GTK_FIXED (fixed8), entry11, 40, 168);
  gtk_widget_set_size_request (entry11, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11), 8226);

  label57 = gtk_label_new (_("Result will be displayed here"));
  gtk_widget_show (label57);
  gtk_fixed_put (GTK_FIXED (fixed8), label57, 72, 400);
  gtk_widget_set_size_request (label57, 300, 30);

  label58 = gtk_label_new ("");
  gtk_widget_show (label58);
  gtk_fixed_put (GTK_FIXED (fixed8), label58, 80, 368);
  gtk_widget_set_size_request (label58, 300, 20);

  label49 = gtk_label_new (_("<b><span foreground=\"gray\" font-desc=\"Serif bold 15\"  > Give the Username</span></b>"));
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (fixed8), label49, 0, 32);
  gtk_widget_set_size_request (label49, 280, 40);
  gtk_label_set_use_markup (GTK_LABEL (label49), TRUE);

  label83 = gtk_label_new (_("<b><span font-desc=\" 13\"  > Username </span></b>"));
  gtk_widget_show (label83);
  gtk_fixed_put (GTK_FIXED (fixed8), label83, 56, 104);
  gtk_widget_set_size_request (label83, 150, 30);
  gtk_label_set_use_markup (GTK_LABEL (label83), TRUE);

  label87 = gtk_label_new (_("First Name"));
  gtk_widget_show (label87);
  gtk_fixed_put (GTK_FIXED (fixed8), label87, 352, 48);
  gtk_widget_set_size_request (label87, 100, 30);

  label88 = gtk_label_new (_("Last Name"));
  gtk_widget_show (label88);
  gtk_fixed_put (GTK_FIXED (fixed8), label88, 352, 112);
  gtk_widget_set_size_request (label88, 100, 30);

  label89 = gtk_label_new (_("<b><span font-desc=\" 13\" foreground=\"orange\"  > Username </span></b>"));
  gtk_widget_show (label89);
  gtk_fixed_put (GTK_FIXED (fixed8), label89, 336, 160);
  gtk_widget_set_size_request (label89, 150, 30);
  gtk_label_set_use_markup (GTK_LABEL (label89), TRUE);

  label91 = gtk_label_new (_("Role"));
  gtk_widget_show (label91);
  gtk_fixed_put (GTK_FIXED (fixed8), label91, 360, 272);
  gtk_widget_set_size_request (label91, 100, 30);

  label92 = gtk_label_new ("");
  gtk_widget_show (label92);
  gtk_fixed_put (GTK_FIXED (fixed8), label92, 464, 48);
  gtk_widget_set_size_request (label92, 105, 32);

  label93 = gtk_label_new ("");
  gtk_widget_show (label93);
  gtk_fixed_put (GTK_FIXED (fixed8), label93, 456, 112);
  gtk_widget_set_size_request (label93, 113, 32);

  label94 = gtk_label_new ("");
  gtk_widget_show (label94);
  gtk_fixed_put (GTK_FIXED (fixed8), label94, 456, 152);
  gtk_widget_set_size_request (label94, 144, 40);

  label90 = gtk_label_new (_("Password"));
  gtk_widget_show (label90);
  gtk_fixed_put (GTK_FIXED (fixed8), label90, 360, 216);
  gtk_widget_set_size_request (label90, 100, 30);

  label95 = gtk_label_new ("");
  gtk_widget_show (label95);
  gtk_fixed_put (GTK_FIXED (fixed8), label95, 472, 208);
  gtk_widget_set_size_request (label95, 96, 32);

  label96 = gtk_label_new ("");
  gtk_widget_show (label96);
  gtk_fixed_put (GTK_FIXED (fixed8), label96, 456, 264);
  gtk_widget_set_size_request (label96, 96, 40);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed8), button2, 392, 360);
  gtk_widget_set_size_request (button2, 150, 40);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button2), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image15 = gtk_image_new_from_stock ("gtk-go-down", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox9), image15, FALSE, FALSE, 0);

  label53 = gtk_label_new_with_mnemonic (_("Display Users"));
  gtk_widget_show (label53);
  gtk_box_pack_start (GTK_BOX (hbox9), label53, FALSE, FALSE, 0);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_fixed_put (GTK_FIXED (fixed8), vseparator1, 264, 8);
  gtk_widget_set_size_request (vseparator1, 152, 464);

  button_search = gtk_button_new ();
  gtk_widget_show (button_search);
  gtk_fixed_put (GTK_FIXED (fixed8), button_search, 16, 320);
  gtk_widget_set_size_request (button_search, 128, 48);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button_search), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image12 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox6), image12, FALSE, FALSE, 0);

  label42 = gtk_label_new_with_mnemonic (_("Search"));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox6), label42, FALSE, FALSE, 0);

  label104 = gtk_label_new (_("label104"));
  gtk_widget_show (label104);
  gtk_fixed_put (GTK_FIXED (fixed8), label104, 96, 288);
  gtk_widget_set_size_request (label104, 168, 32);

  comboboxZA = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxZA);
  gtk_fixed_put (GTK_FIXED (fixed8), comboboxZA, 48, 248);
  gtk_widget_set_size_request (comboboxZA, 149, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxZA), _("ExistorNot"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxZA), _("AllIInformation"));
  gtk_combo_box_set_focus_on_click (GTK_COMBO_BOX (comboboxZA), FALSE);

  label28 = gtk_label_new (_("<b><span foreground=\"turquoise\" >FIND</span></b>"));
  gtk_widget_show (label28);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label28);
  gtk_widget_set_size_request (label28, 100, 30);
  gtk_label_set_use_markup (GTK_LABEL (label28), TRUE);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed9);

  entry12 = gtk_entry_new ();
  gtk_widget_show (entry12);
  gtk_fixed_put (GTK_FIXED (fixed9), entry12, 136, 216);
  gtk_widget_set_size_request (entry12, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12), 8226);

  entry13 = gtk_entry_new ();
  gtk_widget_show (entry13);
  gtk_fixed_put (GTK_FIXED (fixed9), entry13, 136, 264);
  gtk_widget_set_size_request (entry13, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry13), 8226);

  entry14 = gtk_entry_new ();
  gtk_widget_show (entry14);
  gtk_fixed_put (GTK_FIXED (fixed9), entry14, 128, 88);
  gtk_widget_set_size_request (entry14, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry14), 8226);

  entry15 = gtk_entry_new ();
  gtk_widget_show (entry15);
  gtk_fixed_put (GTK_FIXED (fixed9), entry15, 136, 320);
  gtk_widget_set_size_request (entry15, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry15), 8226);

  spinbutton3_adj = gtk_adjustment_new (1, 1, 6, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbutton3, 152, 376);
  gtk_widget_set_size_request (spinbutton3, 70, 34);

  label45 = gtk_label_new (_("Username"));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed9), label45, 16, 88);
  gtk_widget_set_size_request (label45, 100, 30);

  label69 = gtk_label_new (_("<b><span foreground=\"gray\" font-desc=\"Serif bold 13\"  > who you wanna update ? </span></b>"));
  gtk_widget_show (label69);
  gtk_fixed_put (GTK_FIXED (fixed9), label69, 40, 24);
  gtk_widget_set_size_request (label69, 272, 40);
  gtk_label_set_use_markup (GTK_LABEL (label69), TRUE);

  label70 = gtk_label_new (_("<b><span foreground=\"gray\" font-desc=\"Serif bold 13\"  > The new information </span></b>"));
  gtk_widget_show (label70);
  gtk_fixed_put (GTK_FIXED (fixed9), label70, 48, 160);
  gtk_widget_set_size_request (label70, 232, 24);
  gtk_label_set_use_markup (GTK_LABEL (label70), TRUE);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed9), button3, 408, 256);
  gtk_widget_set_size_request (button3, 150, 40);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button3), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image16 = gtk_image_new_from_stock ("gtk-go-down", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox10), image16, FALSE, FALSE, 0);

  label54 = gtk_label_new_with_mnemonic (_("Display Users"));
  gtk_widget_show (label54);
  gtk_box_pack_start (GTK_BOX (hbox10), label54, FALSE, FALSE, 0);

  Update_Update = gtk_button_new ();
  gtk_widget_show (Update_Update);
  gtk_fixed_put (GTK_FIXED (fixed9), Update_Update, 408, 176);
  gtk_widget_set_size_request (Update_Update, 150, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (Update_Update), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image13 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox7), image13, FALSE, FALSE, 0);

  label48 = gtk_label_new_with_mnemonic (_("Update"));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox7), label48, FALSE, FALSE, 0);

  label43 = gtk_label_new (_("First Name"));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed9), label43, 24, 216);
  gtk_widget_set_size_request (label43, 100, 30);

  label44 = gtk_label_new (_("Last Name"));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed9), label44, 24, 272);
  gtk_widget_set_size_request (label44, 100, 30);

  label46 = gtk_label_new (_("Password"));
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed9), label46, 24, 328);
  gtk_widget_set_size_request (label46, 100, 30);

  label47 = gtk_label_new (_("Role"));
  gtk_widget_show (label47);
  gtk_fixed_put (GTK_FIXED (fixed9), label47, 8, 376);
  gtk_widget_set_size_request (label47, 100, 30);

  vseparator3 = gtk_vseparator_new ();
  gtk_widget_show (vseparator3);
  gtk_fixed_put (GTK_FIXED (fixed9), vseparator3, 328, 0);
  gtk_widget_set_size_request (vseparator3, 16, 448);

  label29 = gtk_label_new (_("<b><span foreground=\"turquoise\" >UPDATE</span></b>"));
  gtk_widget_show (label29);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label29);
  gtk_widget_set_size_request (label29, 100, 30);
  gtk_label_set_use_markup (GTK_LABEL (label29), TRUE);

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed11);

  calcul = gtk_button_new ();
  gtk_widget_show (calcul);
  gtk_fixed_put (GTK_FIXED (fixed11), calcul, 200, 304);
  gtk_widget_set_size_request (calcul, 150, 40);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (calcul), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image19 = gtk_image_new_from_stock ("gtk-dialog-question", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox13), image19, FALSE, FALSE, 0);

  label62 = gtk_label_new_with_mnemonic (_("CALCULATE"));
  gtk_widget_show (label62);
  gtk_box_pack_start (GTK_BOX (hbox13), label62, FALSE, FALSE, 0);

  radiobutton7 = gtk_radio_button_new_with_mnemonic (NULL, _("Nombre Total "));
  gtk_widget_show (radiobutton7);
  gtk_fixed_put (GTK_FIXED (fixed11), radiobutton7, 216, 240);
  gtk_widget_set_size_request (radiobutton7, 152, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton7), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton7));

  label60 = gtk_label_new (_("<b><span foreground=\"gray\" font-desc=\"Serif bold 13\"  >  Check according to your choice </span></b>"));
  gtk_widget_show (label60);
  gtk_fixed_put (GTK_FIXED (fixed11), label60, 80, 32);
  gtk_widget_set_size_request (label60, 356, 56);
  gtk_label_set_use_markup (GTK_LABEL (label60), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label60), 0.49, 0.5);

  radiobutton5 = gtk_radio_button_new_with_mnemonic (NULL, _("Restaurent Agent"));
  gtk_widget_show (radiobutton5);
  gtk_fixed_put (GTK_FIXED (fixed11), radiobutton5, 416, 128);
  gtk_widget_set_size_request (radiobutton5, 168, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton5), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton5));

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("Admin "));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed11), radiobutton1, 24, 128);
  gtk_widget_set_size_request (radiobutton1, 116, 23);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobutton1), TRUE);

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("Technicien"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed11), radiobutton2, 24, 176);
  gtk_widget_set_size_request (radiobutton2, 116, 23);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, _("Foyer Agent"));
  gtk_widget_show (radiobutton4);
  gtk_fixed_put (GTK_FIXED (fixed11), radiobutton4, 224, 176);
  gtk_widget_set_size_request (radiobutton4, 116, 23);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  radiobutton6 = gtk_radio_button_new_with_mnemonic (NULL, _("Student "));
  gtk_widget_show (radiobutton6);
  gtk_fixed_put (GTK_FIXED (fixed11), radiobutton6, 416, 176);
  gtk_widget_set_size_request (radiobutton6, 116, 23);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton6), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton6));

  label63 = gtk_label_new ("");
  gtk_widget_show (label63);
  gtk_fixed_put (GTK_FIXED (fixed11), label63, 384, 384);
  gtk_widget_set_size_request (label63, 100, 30);

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, _("Nutrionist"));
  gtk_widget_show (radiobutton3);
  gtk_fixed_put (GTK_FIXED (fixed11), radiobutton3, 224, 128);
  gtk_widget_set_size_request (radiobutton3, 116, 23);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  label61 = gtk_label_new (_("The result will be displayed here"));
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (fixed11), label61, 48, 368);
  gtk_widget_set_size_request (label61, 240, 56);

  label59 = gtk_label_new (_("<b><span foreground=\"turquoise\" >Student Number</span></b>"));
  gtk_widget_show (label59);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), label59);
  gtk_widget_set_size_request (label59, 150, -1);
  gtk_label_set_use_markup (GTK_LABEL (label59), TRUE);

  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_button6_Logout_clicked),
                    NULL);
  g_signal_connect ((gpointer) add_add, "clicked",
                    G_CALLBACK (on_add_add_clicked),
                    NULL);
  g_signal_connect ((gpointer) Display_add, "clicked",
                    G_CALLBACK (on_Display_add_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_Display_add_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonno, "toggled",
                    G_CALLBACK (on_checkbuttonno_toggled),
                    NULL);
  g_signal_connect ((gpointer) Delete, "clicked",
                    G_CALLBACK (on_Delete_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbuttonyes, "toggled",
                    G_CALLBACK (on_checkbuttonyes_toggled),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_Display_add_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_search, "clicked",
                    G_CALLBACK (on_button_search_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_Display_add_clicked),
                    NULL);
  g_signal_connect ((gpointer) Update_Update, "clicked",
                    G_CALLBACK (on_Update_Update_clicked),
                    NULL);
  g_signal_connect ((gpointer) calcul, "clicked",
                    G_CALLBACK (on_calcul_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton7, "toggled",
                    G_CALLBACK (on_radiobutton7_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton5, "toggled",
                    G_CALLBACK (on_radiobutton5_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1, "toggled",
                    G_CALLBACK (on_radiobutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2, "toggled",
                    G_CALLBACK (on_radiobutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton4, "toggled",
                    G_CALLBACK (on_radiobutton4_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton6, "toggled",
                    G_CALLBACK (on_radiobutton6_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton3, "toggled",
                    G_CALLBACK (on_radiobutton3_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Admin, Admin, "Admin");
  GLADE_HOOKUP_OBJECT (Admin, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Admin, welcome, "welcome");
  GLADE_HOOKUP_OBJECT (Admin, button6, "button6");
  GLADE_HOOKUP_OBJECT (Admin, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (Admin, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (Admin, image22, "image22");
  GLADE_HOOKUP_OBJECT (Admin, label97, "label97");
  GLADE_HOOKUP_OBJECT (Admin, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (Admin, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (Admin, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (Admin, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (Admin, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (Admin, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (Admin, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (Admin, add_add, "add_add");
  GLADE_HOOKUP_OBJECT (Admin, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Admin, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Admin, image9, "image9");
  GLADE_HOOKUP_OBJECT (Admin, label37, "label37");
  GLADE_HOOKUP_OBJECT (Admin, label33, "label33");
  GLADE_HOOKUP_OBJECT (Admin, label32, "label32");
  GLADE_HOOKUP_OBJECT (Admin, label31, "label31");
  GLADE_HOOKUP_OBJECT (Admin, label51, "label51");
  GLADE_HOOKUP_OBJECT (Admin, Display_add, "Display_add");
  GLADE_HOOKUP_OBJECT (Admin, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Admin, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Admin, image10, "image10");
  GLADE_HOOKUP_OBJECT (Admin, label38, "label38");
  GLADE_HOOKUP_OBJECT (Admin, label86, "label86");
  GLADE_HOOKUP_OBJECT (Admin, label36, "label36");
  GLADE_HOOKUP_OBJECT (Admin, label103, "label103");
  GLADE_HOOKUP_OBJECT (Admin, label71, "label71");
  GLADE_HOOKUP_OBJECT (Admin, label34, "label34");
  GLADE_HOOKUP_OBJECT (Admin, label35, "label35");
  GLADE_HOOKUP_OBJECT (Admin, vseparator2, "vseparator2");
  GLADE_HOOKUP_OBJECT (Admin, label26, "label26");
  GLADE_HOOKUP_OBJECT (Admin, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (Admin, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (Admin, label50, "label50");
  GLADE_HOOKUP_OBJECT (Admin, label39, "label39");
  GLADE_HOOKUP_OBJECT (Admin, button1, "button1");
  GLADE_HOOKUP_OBJECT (Admin, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (Admin, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (Admin, image14, "image14");
  GLADE_HOOKUP_OBJECT (Admin, label52, "label52");
  GLADE_HOOKUP_OBJECT (Admin, label98, "label98");
  GLADE_HOOKUP_OBJECT (Admin, checkbuttonno, "checkbuttonno");
  GLADE_HOOKUP_OBJECT (Admin, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (Admin, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (Admin, image24, "image24");
  GLADE_HOOKUP_OBJECT (Admin, label100, "label100");
  GLADE_HOOKUP_OBJECT (Admin, Delete, "Delete");
  GLADE_HOOKUP_OBJECT (Admin, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (Admin, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (Admin, image11, "image11");
  GLADE_HOOKUP_OBJECT (Admin, label40, "label40");
  GLADE_HOOKUP_OBJECT (Admin, checkbuttonyes, "checkbuttonyes");
  GLADE_HOOKUP_OBJECT (Admin, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (Admin, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (Admin, image23, "image23");
  GLADE_HOOKUP_OBJECT (Admin, label99, "label99");
  GLADE_HOOKUP_OBJECT (Admin, label101, "label101");
  GLADE_HOOKUP_OBJECT (Admin, label102, "label102");
  GLADE_HOOKUP_OBJECT (Admin, label27, "label27");
  GLADE_HOOKUP_OBJECT (Admin, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (Admin, entry11, "entry11");
  GLADE_HOOKUP_OBJECT (Admin, label57, "label57");
  GLADE_HOOKUP_OBJECT (Admin, label58, "label58");
  GLADE_HOOKUP_OBJECT (Admin, label49, "label49");
  GLADE_HOOKUP_OBJECT (Admin, label83, "label83");
  GLADE_HOOKUP_OBJECT (Admin, label87, "label87");
  GLADE_HOOKUP_OBJECT (Admin, label88, "label88");
  GLADE_HOOKUP_OBJECT (Admin, label89, "label89");
  GLADE_HOOKUP_OBJECT (Admin, label91, "label91");
  GLADE_HOOKUP_OBJECT (Admin, label92, "label92");
  GLADE_HOOKUP_OBJECT (Admin, label93, "label93");
  GLADE_HOOKUP_OBJECT (Admin, label94, "label94");
  GLADE_HOOKUP_OBJECT (Admin, label90, "label90");
  GLADE_HOOKUP_OBJECT (Admin, label95, "label95");
  GLADE_HOOKUP_OBJECT (Admin, label96, "label96");
  GLADE_HOOKUP_OBJECT (Admin, button2, "button2");
  GLADE_HOOKUP_OBJECT (Admin, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (Admin, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (Admin, image15, "image15");
  GLADE_HOOKUP_OBJECT (Admin, label53, "label53");
  GLADE_HOOKUP_OBJECT (Admin, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (Admin, button_search, "button_search");
  GLADE_HOOKUP_OBJECT (Admin, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (Admin, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (Admin, image12, "image12");
  GLADE_HOOKUP_OBJECT (Admin, label42, "label42");
  GLADE_HOOKUP_OBJECT (Admin, label104, "label104");
  GLADE_HOOKUP_OBJECT (Admin, comboboxZA, "comboboxZA");
  GLADE_HOOKUP_OBJECT (Admin, label28, "label28");
  GLADE_HOOKUP_OBJECT (Admin, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (Admin, entry12, "entry12");
  GLADE_HOOKUP_OBJECT (Admin, entry13, "entry13");
  GLADE_HOOKUP_OBJECT (Admin, entry14, "entry14");
  GLADE_HOOKUP_OBJECT (Admin, entry15, "entry15");
  GLADE_HOOKUP_OBJECT (Admin, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (Admin, label45, "label45");
  GLADE_HOOKUP_OBJECT (Admin, label69, "label69");
  GLADE_HOOKUP_OBJECT (Admin, label70, "label70");
  GLADE_HOOKUP_OBJECT (Admin, button3, "button3");
  GLADE_HOOKUP_OBJECT (Admin, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (Admin, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (Admin, image16, "image16");
  GLADE_HOOKUP_OBJECT (Admin, label54, "label54");
  GLADE_HOOKUP_OBJECT (Admin, Update_Update, "Update_Update");
  GLADE_HOOKUP_OBJECT (Admin, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (Admin, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (Admin, image13, "image13");
  GLADE_HOOKUP_OBJECT (Admin, label48, "label48");
  GLADE_HOOKUP_OBJECT (Admin, label43, "label43");
  GLADE_HOOKUP_OBJECT (Admin, label44, "label44");
  GLADE_HOOKUP_OBJECT (Admin, label46, "label46");
  GLADE_HOOKUP_OBJECT (Admin, label47, "label47");
  GLADE_HOOKUP_OBJECT (Admin, vseparator3, "vseparator3");
  GLADE_HOOKUP_OBJECT (Admin, label29, "label29");
  GLADE_HOOKUP_OBJECT (Admin, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (Admin, calcul, "calcul");
  GLADE_HOOKUP_OBJECT (Admin, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (Admin, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (Admin, image19, "image19");
  GLADE_HOOKUP_OBJECT (Admin, label62, "label62");
  GLADE_HOOKUP_OBJECT (Admin, radiobutton7, "radiobutton7");
  GLADE_HOOKUP_OBJECT (Admin, label60, "label60");
  GLADE_HOOKUP_OBJECT (Admin, radiobutton5, "radiobutton5");
  GLADE_HOOKUP_OBJECT (Admin, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (Admin, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (Admin, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT (Admin, radiobutton6, "radiobutton6");
  GLADE_HOOKUP_OBJECT (Admin, label63, "label63");
  GLADE_HOOKUP_OBJECT (Admin, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (Admin, label61, "label61");
  GLADE_HOOKUP_OBJECT (Admin, label59, "label59");

  return Admin;
}

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed10;
  GtkWidget *treeview1;
  GtkWidget *Back;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image17;
  GtkWidget *label55;
  GtkWidget *Refrech;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image18;
  GtkWidget *label56;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window1, 600, 600);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (window1), fixed10);
  gtk_widget_set_size_request (fixed10, 600, 600);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed10), treeview1, 48, 48);
  gtk_widget_set_size_request (treeview1, 500, 400);
  gtk_container_set_border_width (GTK_CONTAINER (treeview1), 677);

  Back = gtk_button_new ();
  gtk_widget_show (Back);
  gtk_fixed_put (GTK_FIXED (fixed10), Back, 128, 480);
  gtk_widget_set_size_request (Back, 100, 40);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (Back), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image17 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox11), image17, FALSE, FALSE, 0);

  label55 = gtk_label_new_with_mnemonic (_("Back"));
  gtk_widget_show (label55);
  gtk_box_pack_start (GTK_BOX (hbox11), label55, FALSE, FALSE, 0);

  Refrech = gtk_button_new ();
  gtk_widget_show (Refrech);
  gtk_fixed_put (GTK_FIXED (fixed10), Refrech, 312, 480);
  gtk_widget_set_size_request (Refrech, 100, 40);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (Refrech), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image18 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox12), image18, FALSE, FALSE, 0);

  label56 = gtk_label_new_with_mnemonic (_("Refrech"));
  gtk_widget_show (label56);
  gtk_box_pack_start (GTK_BOX (hbox12), label56, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) Back, "clicked",
                    G_CALLBACK (on_Back_clicked),
                    NULL);
  g_signal_connect ((gpointer) Refrech, "clicked",
                    G_CALLBACK (on_Refrech_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (window1, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (window1, Back, "Back");
  GLADE_HOOKUP_OBJECT (window1, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (window1, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (window1, image17, "image17");
  GLADE_HOOKUP_OBJECT (window1, label55, "label55");
  GLADE_HOOKUP_OBJECT (window1, Refrech, "Refrech");
  GLADE_HOOKUP_OBJECT (window1, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (window1, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window1, image18, "image18");
  GLADE_HOOKUP_OBJECT (window1, label56, "label56");

  gtk_widget_grab_focus (treeview1);
  return window1;
}

GtkWidget*
create_Window2 (void)
{
  GtkWidget *Window2;
  GtkWidget *fixed12;
  GtkWidget *button5;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image21;
  GtkWidget *label82;
  GtkWidget *label73;
  GtkWidget *label74;
  GtkWidget *label75;
  GtkWidget *label84;
  GtkWidget *label76;
  GtkWidget *label77;
  GtkWidget *label78;
  GtkWidget *label79;
  GtkWidget *label80;
  GtkWidget *label85;
  GtkWidget *label81;

  Window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Window2), _("About your search "));

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (Window2), fixed12);
  gtk_widget_set_size_request (fixed12, 500, 500);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed12), button5, 136, 328);
  gtk_widget_set_size_request (button5, 100, 40);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button5), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image21 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox15), image21, FALSE, FALSE, 0);

  label82 = gtk_label_new_with_mnemonic (_("Back"));
  gtk_widget_show (label82);
  gtk_box_pack_start (GTK_BOX (hbox15), label82, FALSE, FALSE, 0);

  label73 = gtk_label_new (_("<b><span foreground=\"green\" font-desc=\"bold 14\">User found </span></b>"));
  gtk_widget_show (label73);
  gtk_fixed_put (GTK_FIXED (fixed12), label73, 120, 24);
  gtk_widget_set_size_request (label73, 136, 40);
  gtk_label_set_use_markup (GTK_LABEL (label73), TRUE);

  label74 = gtk_label_new (_("First Name"));
  gtk_widget_show (label74);
  gtk_fixed_put (GTK_FIXED (fixed12), label74, 64, 96);
  gtk_widget_set_size_request (label74, 100, 30);

  label75 = gtk_label_new (_("Last Name"));
  gtk_widget_show (label75);
  gtk_fixed_put (GTK_FIXED (fixed12), label75, 64, 144);
  gtk_widget_set_size_request (label75, 100, 30);

  label84 = gtk_label_new (_("<b><span font-desc=\" 13\" foreground=\"orange\"  > Username </span></b>"));
  gtk_widget_show (label84);
  gtk_fixed_put (GTK_FIXED (fixed12), label84, 48, 192);
  gtk_widget_set_size_request (label84, 150, 30);
  gtk_label_set_use_markup (GTK_LABEL (label84), TRUE);

  label76 = gtk_label_new (_("Password"));
  gtk_widget_show (label76);
  gtk_fixed_put (GTK_FIXED (fixed12), label76, 72, 248);
  gtk_widget_set_size_request (label76, 100, 30);

  label77 = gtk_label_new (_("Role"));
  gtk_widget_show (label77);
  gtk_fixed_put (GTK_FIXED (fixed12), label77, 64, 288);
  gtk_widget_set_size_request (label77, 100, 30);

  label78 = gtk_label_new ("");
  gtk_widget_show (label78);
  gtk_fixed_put (GTK_FIXED (fixed12), label78, 208, 88);
  gtk_widget_set_size_request (label78, 256, 48);

  label79 = gtk_label_new ("");
  gtk_widget_show (label79);
  gtk_fixed_put (GTK_FIXED (fixed12), label79, 224, 136);
  gtk_widget_set_size_request (label79, 256, 48);

  label80 = gtk_label_new ("");
  gtk_widget_show (label80);
  gtk_fixed_put (GTK_FIXED (fixed12), label80, 224, 200);
  gtk_widget_set_size_request (label80, 256, 40);

  label85 = gtk_label_new ("");
  gtk_widget_show (label85);
  gtk_fixed_put (GTK_FIXED (fixed12), label85, 240, 280);
  gtk_widget_set_size_request (label85, 248, 56);

  label81 = gtk_label_new ("");
  gtk_widget_show (label81);
  gtk_fixed_put (GTK_FIXED (fixed12), label81, 216, 336);
  gtk_widget_set_size_request (label81, 296, 88);

  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_Back_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Window2, Window2, "Window2");
  GLADE_HOOKUP_OBJECT (Window2, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (Window2, button5, "button5");
  GLADE_HOOKUP_OBJECT (Window2, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (Window2, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (Window2, image21, "image21");
  GLADE_HOOKUP_OBJECT (Window2, label82, "label82");
  GLADE_HOOKUP_OBJECT (Window2, label73, "label73");
  GLADE_HOOKUP_OBJECT (Window2, label74, "label74");
  GLADE_HOOKUP_OBJECT (Window2, label75, "label75");
  GLADE_HOOKUP_OBJECT (Window2, label84, "label84");
  GLADE_HOOKUP_OBJECT (Window2, label76, "label76");
  GLADE_HOOKUP_OBJECT (Window2, label77, "label77");
  GLADE_HOOKUP_OBJECT (Window2, label78, "label78");
  GLADE_HOOKUP_OBJECT (Window2, label79, "label79");
  GLADE_HOOKUP_OBJECT (Window2, label80, "label80");
  GLADE_HOOKUP_OBJECT (Window2, label85, "label85");
  GLADE_HOOKUP_OBJECT (Window2, label81, "label81");

  return Window2;
}

