/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Sign_up (void);
GtkWidget* create_Login (void);
GtkWidget* create_Admin (void);
GtkWidget* create_window1 (void);
GtkWidget* create_Window2 (void);
