/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Sign_up;
  GtkWidget *Login;
  GtkWidget *Admin;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  
  Login = create_Login ();
  gtk_widget_show (Login);
  

  gtk_main ();
  return 0;
}/*
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "fonction.c"
#include "fonction.h"
#define Filename user.txt
int main() ;
{
char ch[50];
user u;
int x ;*/
		/*printf("First Name :");
		scanf("%s",u.First_Name);

		printf("Last Name :");
		scanf("%s",u.Last_Name);

		printf("Username :");
		scanf("%s",u.Username);

		printf("Password :");
		scanf("%s",u.Password);

		printf("Role :");
		scanf("%d",&u.Role);
		add_user(u);*/
		
		/*printf("Username :");
		scanf("%s",u.Username);
		delete_user(u.Username) ;*/

		/*printf("Username to find :");
		scanf("%s",ch);
		if(find_user(ch))
		printf("username %s is here !!! \n",ch);
		else
		printf("username %s Not Found!! \n",ch);*/
		
		/*printf("Username :");
		scanf("%s",ch);		
		display_user_info(ch);*/




	/*printf("\t \t-------------MENU-------------\n\n ") ; 
	printf("veillez choisir l'action que vous voulez faire \n  1-) Add user \n 2-)Delete user \n 3-)Update user \n 4-)Find user \n 5-)Display user \n 6-)Student Number \n " ) ;
	scanf("%d", &x) ;
	switch( x ){	
	case 1 :
		
			
		printf("First Name : \n");
               fflush(stdin);
		scanf(" %s",u.First_Name);
		//printf("%s",u.First_Name) ;
		printf("Last Name :\n");
		scanf("%s",u.Last_Name);		
		//gets(u.Last_Name);
		
		printf("Username :\n");
		scanf("%s",u.Username);

		printf("Password :\n");
		scanf("%s",u.Password);

		printf("Role :");
		scanf("%d",&u.Role);
		add_user(u);
		break ;
	case 2 :
		{
		printf("Username :");
		scanf("%s",u.Username);
		delete_user(u.Username) ;
		}
	case 4 :
		{
		printf("Username to find :");
		scanf("%s",ch);
		if(find_user(ch))
		printf("username %s is here !!! \n",ch);
		else
		printf("username %s Not Found!! \n",ch);
		}
	case 5 :
		{
		printf("Username :");
		scanf("%s",ch);		
		display_user_info(ch);
		}		
	case 3 :
		{
		printf("Username :");
		scanf("%s",u.Username);		
		update_user(u,ch);
		}


	}




return 0;
}*/
